[package]
name = "ina3221_async"
version = "0.1.0"
authors = [
  "Erik Rogers <erik@underlogic.tech>",
  "Dmytro Krasnianskyi <k.dimonych@gmail.com>",
]
edition = "2024"
repository = "https://github.com/kdimonych/ina3221_async"
license = "MIT"
description = "Async embedded driver for INA3221 triple-channel power monitor using embedded-hal-async"
readme = "README.md"
keywords = ["i2c", "driver", "embedded-hal-driver", "ina3221", "power"]
categories = ["embedded", "hardware-support", "no-std"]

[dependencies]
bitflags = "1.3.2"
embedded-hal = "1.0.0-alpha.9"
ohms = "0.2.0"
